# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170913_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
