# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pakutter', '0004_auto_20170908_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pakutter.User'),
        ),
    ]
